apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api-app
    template:
      metadata:
        labels:
          app: fast-api-app
      spec:
        containers:
          - name: fast-api-app-container
            image: lolkek1415/fast-api
            ports:
              - containerPort: 5000
                protocol: TCP