version: '3.10'

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    env_file:
      - .env